on:
  push:
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Stamp tag
        id: stamp
        run: |
          echo "tag=r$(date +'%Y%m%d.%H%M%S')-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

#      - name: Create tag & push
#        run: |
#          git tag ${{ steps.stamp.outputs.tag }}
#          git push origin --tags

      - name: Create Github Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create ${{ steps.stamp.outputs.tag }} --generate-notes

#      - name: Create Github Release
#        uses: softprops/action-gh-release@v1
#        with:
#          tag_name: ${{ steps.stamp.outputs.tag }}
#          generate_release_notes: true
