on:
  push:
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: create and push tag
        id: stamp
        run: |
          echo "tag=r$(date +'%Y%m%d.%H%M%S')-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          git tag ${{ steps.stamp.outputs.tag }}
          git push origin --tags
