on:
  push:
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-22.04
    steps:
      - name: create and push tag
        run: |
          echo "RELEASE_TAG=r$(date +'%Y%m%d.%H%M%S')-${{ github.sha }}" >> $GITHUB_ENV
          git tag ${{ env.RELEASE_TAG }}
          git push origin --tags
