name: tag and release

on:
  workflow_dispatch:

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: release

      - name: Stamp tag
        id: stamp
        run: |
          echo "tag=r$(date +'%Y%m%d.%H%M%S')-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Create Github Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create ${{ steps.stamp.outputs.tag }} --generate-notes
